DEFAULT_CONFIG_DICT = {
    'username': {
        "key": "username",
        "name": "username",
        "placeholder": "username",
        "type": 5,
        "username_type": "username",
        "min_length": 4,
        "max_length": 32,
        "is_optional": False,
        "is_editable": False,
        "is_default": True,
    },
    'code': {
        "key": "code",
        "name": "user_id",
        "placeholder": "user_id",
        "type": 5,
        "max_length": 20,
        "is_optional": True,
        "is_editable": False,
    },
    'email': {
        "key": "email",
        "name": "email",
        "placeholder": "email",
        "type": 5,
        "max_length": 100,
        "is_optional": True,
        "is_editable": False,
    },
    'password': {
        "key": "password",
        "name": "password",
        "placeholder": "password",
        "type": 5,
        "min_length": 4,
        "max_length": 32,
        "is_optional": False,
        "is_editable": False,
        "is_default": True,
    },
    'title': {
        "key": "title",
        "name": "title_name",
        "placeholder": "title_name",
        "type": 8,
        "is_optional": True,
        "is_editable": False,
    },
    'first_name': {
        "key": "first_name",
        "name": "first_name",
        "placeholder": "first_name",
        "type": 5,
        "max_length": 100,
        "is_optional": True,
        "is_editable": False,
    },
    'middle_name': {
        "key": "middle_name",
        "name": "middle_name",
        "placeholder": "middle_name",
        "type": 5,
        "max_length": 100,
        "is_optional": True,
        "is_editable": False,
    },
    'last_name': {
        "key": "last_name",
        "name": "last_name",
        "placeholder": "last_name",
        "type": 5,
        "max_length": 100,
        "is_optional": True,
        "is_editable": False,
    },
    'id_card': {
        "key": "id_card",
        "name": "id_card",
        "placeholder": "id_card",
        "type": 5,
        "max_length": 13,
        "is_optional": True,
        "is_editable": False,
    },
    'code2': {
        "key": "code2",
        "name": "licence_id",
        "placeholder": "licence_id",
        "type": 5,
        "max_length": 20,
        "is_optional": True,
        "is_editable": False,
    },
    'gender': {
        "key": "gender",
        "name": "gender",
        "placeholder": "gender",
        "type": 2,
        "is_optional": True,
        "is_editable": False,
    },
    'date_birth': {
        "key": "date_birth",
        "name": "date_of_birth",
        "placeholder": "date_of_birth",
        "type": 10,
        "is_optional": True,
        "is_editable": False,
    },
    'address': {
        "key": "address",
        "name": "address",
        "placeholder": "address",
        "type": 5,
        "max_length": 2000,
        "is_optional": True,
        "is_editable": False,
    },
    'phone': {
        "key": "phone",
        "name": "phone",
        "placeholder": "phone",
        "type": 5,
        "is_optional": True,
        "is_editable": False,
    },
    'company': {
        "key": "company",
        "name": "company_name",
        "placeholder": "company_name",
        "type": 5,
        "max_length": 200,
        "is_optional": True,
        "is_editable": False,
    },
    'count_experience': {
        "key": "count_experience",
        "name": "year_of_experience",
        "placeholder": "year_of_experience",
        "type": 13,
        "is_optional": True,
        "is_editable": False,
    },

}
