# Generated by Django 3.1.5 on 2021-01-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-is_active', '-id']},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'default_permissions': (), 'ordering': ['-datetime_create']},
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=32, null=True),
        ),
    ]
