# Generated by Django 3.1 on 2020-12-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view', 'view_by_mentor', 'view_by_department', 'view_by_group', 'view_by_level', 'view_by_organization', 'view_by_inspector', 'view_by_instructor', 'view_by_manager', 'view_by_provider', 'view_by_support'),
            },
        ),
    ]
