# Generated by Django 3.1.5 on 2021-01-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registerprofile',
            options={},
        ),
    ]
